### PR TITLE
Upgrade crossterm to 0.12

### PR DESCRIPTION
**Pull request by theduke**

### CODE REVIEW

**Comment by theduke** [comment]
Demo works fine.

**Comment by TimonPost** [comment]
I did some refactoring to the backend, while I wanted to upgrade to 0.12 I saw that this PR was already opened. Maybe we can close this one in favor of: https://github.com/fdehau/tui-rs/pull/195?

**Comment by theduke** [comment]
>  Maybe we can close this one in favor of

Fine with me, although I obviously did put lots of effort into this one.
Okay, 5 minutes... ;)

**Comment by TimonPost** [comment]
Nice, sorry for stealing the already performed work :)

**Pull request closed without merging**
