### PR TITLE
add clear widget and popup example utilizing it

### PR DESCRIPTION
**Pull request by extrawurst**
see #244 and #211

Please give me a first review before I go about documentation.

### CODE REVIEW

**Comment by fdehau** [comment]
The example may be a bit complicated for this feature but otherwise this looks good.

**Comment by extrawurst** [comment]
ok!
I see u plan to release `0.9`: https://github.com/fdehau/tui-rs/issues/254#issuecomment-606694700

how much time do I have to add documentation to be able to get it in for 0.9?

**Comment by fdehau** [comment]
I'm waiting for a stable release of crossterm (i.e with bug fixes for the recent reported issues). I think you'll have a fair amount of time and this could go in a 0.9.1 if not.

**Comment by extrawurst** [comment]
@fdehau docs with doc example added, ready to pull

PS: the crossterm fixes have also landed 👍

**Pull request merged**
