### PR TITLE
Selectable table

### PR DESCRIPTION
**Pull request by sputnick1124**
This adds the option to have a selected item in a `Table` which can be highlighted with a style and symbol (a parallel feature with the `SelectableList` type). The constructor was not changed to avoid breaking existing code. Selectability can be configured using the builder pattern as is common in the rest of the code base.

[asciicast](https://asciinema.org/a/qf6RCoFQL0pn934C2YyySTx5S)

Closes https://github.com/fdehau/tui-rs/issues/196

### CODE REVIEW

**Comment by laumann** [comment]
@sputnick1124 Thank you! I've wanted this feature for some time, but never dug into the implementation myself. I imagine though that you might have to redo the implementation to make it a `StatefulWidget`. (`SelectableList` has been removed.)

**Comment by sputnick1124** [comment]
Glad it'll be useful! I'll take a look at it when I get some time later this month to see what needs to be changed. To be clear, I didn't use `SelectableList` in my implementation, but baked selectability into the current implementation of the `Table` widget. At and rate, this was some time ago now and I assume the PR will need some updating at least.

**Comment by laumann** [comment]
True, I realized that after leaving my comment :-) But I think there's a little more work to be done anyhow. I'm updating my codebase to run off of `master` right now, because I want to see how the `StatefulWidget` trait stuff works out.

**Comment by fdehau** [comment]
@sputnick1124 I built upon your work here to implement the feature in #242. Thanks again for your work and sorry for the late response/review.

**Pull request closed without merging**
