### PR TITLE
Make Text accept both borrowed and owned strings

### PR DESCRIPTION
**Pull request by abusch**
I took a crack at fixing issue #70 and here's what it looks like. The slightly annoying thing is having to add `.into()` when building a `Text`. If that's too annoying we can maybe add some helper methods like `Text::data()` and `Text::styled_data()` that would do the conversion for you.

### CODE REVIEW

**Comment by abusch** [comment]
I added some helper methods `Text::data()` and `Text::styled_data()` to make building `Text` instances a bit easier (i.e without having to call `into()`). Let me know what you think!

Note that if we go with this, it might be worth changing `Item` the same way for consistency (right now it takes an owned string, and reference to a style, which is the exact opposite of `Text`...)

**Comment by fdehau** [comment]
Hi, thanks for taking the time to look into this. I agree with most of the changes.

Item currently requires its data to implements `Display`. It thus works for both owned or borrowed strings but all items should be of the same type. So `Cow` might also be a better idea there, especially when items are created "manually".  As of the `Style`, I think that we should go for an owned version.

An unified definition of `Text` and `Item` could be:

```rust
pub enum Text<'b> {
    Raw(Cow<'b, str>),
    Styled(Cow<'b, str>, Style),
}
```
dropping `Data` in names which appears unnecessary the more I read it.

Let me know what you think...

**Comment by abusch** [comment]
Yes, I think that makes sense. I've implemented this so you can see what it looks like.

**Comment by fdehau** [comment]
Great work :+1: Let me know if you have more feedback on the upcoming release.

**Pull request merged**
