### PR TITLE
refresh current view

### PR DESCRIPTION
**Pull request by uuhan**
Seems this is no way to refresh current view. If there is another good way to do this, please correct me.

The case is, if there are some additional stdout output, the view will become very strange, like this:

issue

Can try with this demo file:

https://github.com/uuhan/tui-rs/blob/9337ad047a45a65f6320efc419178b71205de12e/examples/termion_demo.rs#L56

### CODE REVIEW

**Comment by fdehau** [comment]
If you write to stdout and say to tui it can write to the entire terminal screen, yes things are likely to end up messed up. What are you trying to achieve exactly here ?

**Comment by uuhan** [comment]
> If you write to stdout and say to tui it can write to the entire terminal screen, yes things are likely to end up messed up. What are you trying to achieve exactly here ?

I need a way to refresh the view. I'am working on a quite complex terminal app and it relay's some other libraries and sometimes they may output some message to stdout. I can not control the behavior but I can offer a way to refresh the view, e.g. the user can press 'p' key to reset the view.

**Comment by fdehau** [comment]
Would the new behavior of clear introduced in #360 fit your use case ?

**Comment by fdehau** [comment]
Feel free to reopen if the suggested fix does not work :)

**Pull request closed without merging**
